### ISSUE TITLE
Resourcelib fails to parse Jetbrains' executables resources

### ISSUE THREAD

**Issue by ljani** [resourcelib/resourcelib#38]
Feeding the (64-bit) executables from [Jetbrains'](https://www.jetbrains.com) tools (eg. [[1](https://www.jetbrains.com/webstorm/download/#section=windows-version)], [[2](https://www.jetbrains.com/datagrip/download/#section=windows-version)]) to ResourceLib fails with an exception:

```
Vestris.ResourceLib.LoadException: Error loading 'datagrip64.exe'. Unknown error (0xe0434352).
---> System.Exception: Error loading resource '1' RT_VERSION (1031).
---> System.ArgumentException: Item has already been added. Key in dictionary: '\u0001StringFileInfo'  Key being added: '\u0001StringFileInfo'
   at Vestris.ResourceLib.ResourceInfo.EnumResourceLanguages(IntPtr hModule, IntPtr lpszType, IntPtr lpszName, UInt16 wIDLanguage, IntPtr lParam)
--- End of inner exception stack trace ---
--- End of inner exception stack trace ---
   at Vestris.ResourceLib.ResourceInfo.Load(String filename)
```

**Comment by dblock** [comment]
I would try to make a minimal repro in a test in this project and make a PR with it, to start.

**Comment by ljani** [comment]
Sure thing. It seems that it's only the 64-bit executables that are failing (`idea.exe` was fine).

**Comment by dblock** [comment]
Good, what's the layout of that ResourceInfo block? Now that you have a repro you should be able to debug/fix it :)

**Comment by thoemmi** [comment]
I had a short look at the issue. For whatever reason resourcelib is not able to read a `StringFileInfo` section from that file. It seems to be related to padding, as the key for the resource is read as `\u0001StringFileInfo`. Unfortunately, I can't offer a solution at hand.
