### ISSUE TITLE
IconDirectoryResource.SaveTo has bugs with some .ico file.

### ISSUE THREAD

**Issue by CreateAndInject** [resourcelib/resourcelib#48]
```
   public static void ReplaceIcon(string exeFile, string icoFile)
    {
        ResourceInfo ri = new ResourceInfo();
        ri.Load(exeFile);
        ri.Unload();
        var res=ri[Kernel32.ResourceTypes.RT_GROUP_ICON][0];
        IconDirectoryResource idr = new IconDirectoryResource(new IconFile(icoFile));
        idr.Name = res.Name;
        idr.Language = res.Language;
        idr.SaveTo(exeFile);
    }
```

attach file 0.zip contains a 0.ico
If ReplaceIcon with 0.ico, the target exe will lose icon.
But if I compile a exe with 0.ico by visual studio,it's ok ,so 0.ico is format well.
So, bug?

[0.zip](https://github.com/dblock/resourcelib/files/439457/0.zip)

**Comment by dblock** [comment]
Looks like something is fishy, I would dump and compare all icon resources before/after for all languages.

**Comment by CreateAndInject** [comment]
Do you know why?

**Comment by dblock** [comment]
Sorry, don't have time to debug it. But happy to help if you make some progress.

**Comment by CreateAndInject** [comment]
I find some other .ico files have the same problem, these .ico files all have large size.

**Comment by CreateAndInject** [comment]
any news?

**Comment by dblock** [comment]
@CreateAndInject Did you find a bug and submit a fix? Nobody is working on this.

**Comment by clopezfreedom** [comment]
I had exactly the same bug and found that the problem was that the icon resource indices inside the executable are 1-based instead of 0-based. The following change in IconDirectoryResource.cs solved this issue for me:

        /// <summary>
        /// A new collection of icons that can be embedded into an executable file.
        /// </summary>
        public IconDirectoryResource(IconFile iconFile)
            : base(Kernel32.ResourceTypes.RT_GROUP_ICON)
        {            
            for (UInt16 id = 1; id <= iconFile.Icons.Count; id++)
            {
                IconResource iconResource = new IconResource(
                    iconFile.Icons[id - 1], new ResourceId(id), _language);
                Icons.Add(iconResource);
            }
        }

**Comment by dblock** [comment]
Interesting @clopezfreedom. I don't think that's per spec, but maybe you can dig this up, write a test and a fix?

**Comment by CreateAndInject** [comment]
@clopezfreedom  Nice! Resolve my problem!

**Comment by dblock** [comment]
@CreateAndInject Maybe you want to save the next person the trouble, please see ^^^, lets have a test + fix here?

**Comment by jairbubbles** [comment]
Experiencing the same issue here. After resaving the .exe in Visual Studio we do see the indexes are modified:
![image](https://user-images.githubusercontent.com/15875066/31118396-90a33492-a82d-11e7-9e50-e2057363eeb9.png)

**Comment by jairbubbles** [comment]
I'm patching the icon after loading and it now works perfectly:
```csharp
for (var index = 0; index < icon.Icons.Count; index++)
{
   icon.Icons[index].Id = (ushort)(index + 1);
} 
```

Would be great to make the fix on the NuGet package!

**Comment by dblock** [comment]
@jairbubbles Can you please pull request a failing test and a code fix?
