### ISSUE TITLE
Pb with NuGet version number

### ISSUE THREAD

**Issue by jairbubbles** [resourcelib/resourcelib#50]
Version number in nuspec is 1.5.328.0 which does not match [semantic versioning](http://semver.org/). When you browse on nuget.org the .nupgk that you can download is now `Vestris.ResourceLib.1.5.328.nupkg`, I believe it used to be `Vestris.ResourceLib.1.5.328.0.nupkg` as I noticed on some old computer's nuget cache.

My issue is that when you install the package it still put it in 1.5.328.0 folder which is not what I expect as when I ask for the version it tells me 1.5.328. I guess it uses version from .nuspec:
```xml
<version>1.5.328.0</version>
```

*I don't know what changed this as the package was not published recently (maybe something on the NuGet server to ensure semantic versioning is working?)*

Would it be possible to publish it again with a correct semantic version ?

**Comment by dblock** [comment]
cc: @thoemmi

**Comment by thoemmi** [comment]
I'll have a look tonight.

**Comment by thoemmi** [comment]
Indeed, NuGet does not support the old versioning schema like *major.minor.patch.release* anymore. Instead, [semantic versioning](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning) is required.

I suggest that I publish a 1.6.0 release, which will contain the unreleased fixes for #40 and #41 as well.

BTW, I'd like to update the projects and the build for VS2017, targetting .NET 4.0 and .NET 4.5. @dblock what do you think?

**Comment by dblock** [comment]
I haven't written a line of code here so this is all yours!

Lets move this into an org and make you an admin of it @thoemmi so you can add new contributors?

**Comment by thoemmi** [comment]
Sounds about right. Ok, transfer this repository to an org.

**Comment by dblock** [comment]
Moved. If someone could fix up links, CI and such that'd be great. For now things redirect of course.

**Comment by thoemmi** [comment]
I am going to update the links and prepare und publish a 1.6 release.

Later I'll migrate the source to use VS2017 and set up a new CI pipeline.

**Comment by thoemmi** [comment]
@jairbubbles I just published version 1.6.422, which should be compliant with semantic versioning.

**Comment by jairbubbles** [comment]
@thoemmi Awesome! Thx a lot
