### ISSUE TITLE
Change existing exe File Description and Product Name

### ISSUE THREAD

**Issue by laifharwood** [resourcelib/resourcelib#52]
Is it possible to change the File Description and Product Name with this library?  There is a snippet of code in the Version section that looks like it might be possible but it's unclear and I haven't been able to get it to work if it is possible.

**Comment by dblock** [comment]
Yes, there's a complete example at the bottom of https://github.com/resourcelib/resourcelib/blob/17461f2dd23f064b47780e0168a6da79e894da4f/Docs/Version.md.

**Comment by laifharwood** [comment]
@dblock The code below, which is nearly identical to the example you mentioned, runs without error but doesn't appear to have any affect on the properties of the exe so I don't know if I'm missing something or what. Any help or direction you can provide would be greatly appreciated. If you need any more information let me know. Thanks!

			string filename = "C:/Users/lharwood/Desktop/ProModel.exe";
			VersionResource versionResource = new VersionResource();
			versionResource.FileVersion = "1.2.3.4";
			versionResource.ProductVersion = "4.5.6.7";

			StringFileInfo stringFileInfo = new StringFileInfo();
			versionResource[stringFileInfo.Key] = stringFileInfo;
			StringTable stringFileInfoStrings = new StringTable();
			stringFileInfoStrings.LanguageID = 1033;
			stringFileInfoStrings.CodePage = 1200;
			stringFileInfo.Strings.Add(stringFileInfoStrings.Key, stringFileInfoStrings);
			stringFileInfoStrings["ProductName"] = "MedModel";
			stringFileInfoStrings["FileDescription"] = "MedModel Application";
			stringFileInfoStrings["CompanyName"] = "Vestris Inc.\0"; // \0 is optional, ResourceLib will append it
			stringFileInfoStrings["LegalCopyright"] = "All Rights Reserved";
			stringFileInfoStrings["Comments"] = "This file has a version resource updated by ResourceLib";
			stringFileInfoStrings["ProductVersion"] = string.Format("{0}\0", versionResource.ProductVersion);

			VarFileInfo varFileInfo = new VarFileInfo();
			versionResource[varFileInfo.Key] = varFileInfo;
			VarTable varFileInfoTranslation = new VarTable("Translation");
			varFileInfo.Vars.Add(varFileInfoTranslation.Key, varFileInfoTranslation);
			varFileInfoTranslation[ResourceUtil.USENGLISHLANGID] = 1300;

			versionResource.SaveTo(filename);

**Comment by thoemmi** [comment]
@laifharwood what you're doing in your code is **adding** a **new** version resource to your executable. I guess the executable already has a version resource embedded, so it ends up having two. Windows Explorer will still show the first one.

What you have to do is to update the existing version resource:

```csharp
string filename = "C:/Users/lharwood/Desktop/ProModel.exe";

// load the existing version info
VersionResource versionResource = new VersionResource();
versionResource.Language = 0; // I guess the existing version info has the language id 0
versionResource.LoadFrom(filename);

// update the required parts
StringFileInfo stringFileInfo = (StringFileInfo)versionResource["StringFileInfo"];
stringFileInfo["ProductName"] = "MedModel";
stringFileInfo["FileDescription"] = "MedModel Application";
stringFileInfo["CompanyName"] = "Vestris Inc.\0"; // \0 is optional, ResourceLib will append it
stringFileInfo["LegalCopyright"] = "All Rights Reserved";
stringFileInfo["Comments"] = "This file has a version resource updated by ResourceLib";
stringFileInfo["ProductVersion"] = string.Format("{0}\0", versionResource.ProductVersion);

// write back the updated version resource
versionResource.SaveTo(filename);
```

**Comment by laifharwood** [comment]
@thoemmi That worked! Thank you for your help!
