### ISSUE TITLE
Overflow exception while parsing RT_DIALOG

### ISSUE THREAD

**Issue by theLastOfCats** [resourcelib/resourcelib#53]
* Most of time it happens, when I try to extract Resource from RT_DIALOG with **many fields (>15)** and **NOT** in DIALOGEX format
* If I RT_DIALOG format from DIALOG to DIALOGEX using Resource Hacker, parsing finish successfully
* Maybe related to #10

**Comment by dblock** [comment]
Next step is to find an executable that shows this problem and reproduce it as a test in a pull request.

**Comment by theLastOfCats** [comment]
Bug produce when I set x64 build. Any PC and x86 not affected.

**Comment by theLastOfCats** [comment]
Cannot reproduce bug, will close.

**Comment by dblock** [comment]
x64 would still point to a real problem, maybe you want to dig a bit deeper?
