### ISSUE TITLE
VersionResource can't save to same file after loading from it 

### ISSUE THREAD

**Issue by liu264** [resourcelib/resourcelib#54]
get error “system.componentmodel.win32exception access is denied” when save to same file it loaded from. 
![default](https://user-images.githubusercontent.com/24662144/29738206-b3b292f8-8a4f-11e7-8adb-bc822d7bc8bc.png)

**Comment by dblock** [comment]
Do you have permission to read, but not write the file? Maybe it's in use by another program?

**Comment by liu264** [comment]
Permission is good. I am bypassing this issue by creating a copy, read from copy, and write back to the original file.

**Comment by dblock** [comment]
Does it work without the first two lines? I think your file is simply still open and you need to close it.

**Comment by liu264** [comment]
It threw mix-language exception so I need to provide that info. I guess I can hard code it for now, but still. Is ResourceInfo disposable?

**Comment by dblock** [comment]
Yep, https://github.com/resourcelib/resourcelib/blob/master/Source/ResourceLib/ResourceInfo.cs#L13.

**Comment by dblock** [comment]
Do confirm please whether that's the problem, we don't want to be leaking handles in `LoadFrom` and `SaveTo`.

**Comment by liu264** [comment]
yap, disposing ResourceInfo works, thanks
