### ISSUE TITLE
Version update bug

### ISSUE THREAD

**Issue by liu264** [resourcelib/resourcelib#55]
When changing version number, the file version is properly updated, but the product version's not
![default](https://user-images.githubusercontent.com/24662144/29738386-d0bc9d72-8a53-11e7-973f-b27ee6a63efd.png)
Even though when reading back from the file the product version is changed indeed. Perhaps product version read and wrote the same element as file version.
![default](https://user-images.githubusercontent.com/24662144/29738381-ae613706-8a53-11e7-95eb-e25d2ea96db5.png)
Additionally, for dll files, it's the same situation for both file version and product version. I can read it back to see the changes but when open file properties it's still the old version number.

**Comment by dblock** [comment]
You're most likely seeing ProductVersion from the string info and not from this value, check out the details in https://github.com/resourcelib/resourcelib/blob/17461f2dd23f064b47780e0168a6da79e894da4f/Docs/Version.md, there're two product version fields.

**Comment by liu264** [comment]
Thanks, I think I tried the stringFileInfoStrings as well, but can't be sure (it's been a long day). I will try again on Monday.

**Comment by liu264** [comment]
Thanks it works, partially, changing the StringFileInfo solved that ProductVersion issue for my exe, but for my dll neither one of the version numbers are changed still. Does dll file have a different data structure?

**Comment by liu264** [comment]
Thanks that works! and I had to restore the dll file to make that work for it. Propably something I did before with this program that changed some data within to it unchangable before.
