### ISSUE TITLE
Need library depending on framework runtime v4.0

### ISSUE THREAD

**Issue by MarkoKaiser** [resourcelib/resourcelib#61]
For a future development process I need the library depend on .NET framework runtime v4.0 instead of v2.0.

**Comment by thoemmi** [comment]
Please try the newest pre-release [2.0.0-ci0018](https://www.nuget.org/packages/Vestris.ResourceLib/2.0.0-ci0018). It supports .NET Frameworks 2.0, 3.5, 4.0, and 4.5 and .NET Standard 2.0.
 We'll publish a final release as soon as *System.Drawing.Common* is made final (required to support .NET Standard 2.0).

**Comment by MarkoKaiser** [comment]
Ok thank you that pre-release works :)
