### ISSUE TITLE
The problem of saving Icon

### ISSUE THREAD

**Issue by SilkageNet** [resourcelib/resourcelib#65]
```
using (ResourceInfo vi = new ResourceInfo())
            {
                vi.Load(filename);
                var resKey = vi.Resources.Keys.FirstOrDefault(v => v.ResourceType == Kernel32.ResourceTypes.RT_GROUP_ICON);
                if (resKey == null) return;
                var res = vi.Resources[resKey];
                var iconRes = res[0] as IconDirectoryResource;
                var icon = iconRes.Icons.OrderByDescending(i => i.ImageSize).FirstOrDefault();
                icon.Image.Image.Save("1.ico");
                icon.Image.Color.Save("2.ico");
            }
```

The height of ‘1.ico’ is two times as high as normal.
If the resource icon is partially transparent, the transparent part after storage becomes black.
Excuse me, what's the solution?

**Comment by dblock** [comment]
Looks like a bug, please feel free to debug and PR a fix.

**Comment by SilkageNet** [comment]
Is there any other way to save IconDirectoryResource as *.icon file?

**Comment by icnocop** [comment]
> Is there any other way to save IconDirectoryResource as *.icon file?

See https://github.com/resourcelib/resourcelib/issues/36
