### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [resourcelib/resourcelib#67]
Maybe @hakito can do the next release? @thoemmi and I can help

We could use a RELEASING like [this one](https://github.com/dblock/iex-ruby-client/blob/master/RELEASING.md).

**Comment by thoemmi** [comment]
I've added this issue to the v2.0 milestone.

Because vNext will provide support for .NET Standard, we're depending on **System.Drawing.Common**, which is available as a preview only at the moment. I expect the final release next week during Microsoft's Build conference.
It's filed as #63

**Comment by hakito** [comment]
Did you have time to look at PR #68? I wanted to discuss it first before pushing it to the main repo. At least 292dc2384c55d66eaf9ad5d8049dd947be74fcc0 should get into the release.

**Comment by hakito** [comment]
@dblock What exactly do you mean with 

> We could use a RELEASING like this one.

It seems https://github.com/resourcelib/resourcelib/blob/master/appveyor.yml already creates and publishes the .nupkg it seems. It could also create a github pre-release.

I have a question regarding the version number: We are going from 1.6 to 2.0 - are there really breaking changes?

**Comment by thoemmi** [comment]
That's right. A couple of month ago I created an AppVeyor configuration which publishes each build from the master branch to NuGet.
Additionally, the build process uses [GitVersion](https://gitversion.readthedocs.io/en/latest/) to generate semantic version numbers. 

> I have a question regarding the version number: We are going from 1.6 to 2.0 - are there really breaking changes?

I've re-written the project files to use the new MSBuild SDK format. Also we're now supporting .NET Standard 2.0. Though there'no API changes, IMHO the changes the under the hood justify a major release.

**Comment by dblock** [comment]
Since I co-maintain a lot of different projects I always wonder "how do I release this thing". So even if RELEASING says there's nothing to do, it's good to have.

**Comment by thoemmi** [comment]
Ok, I'll create a RELEASING file.

**Comment by hakito** [comment]
I can then try to do the release according to it.

**Comment by dblock** [comment]
From https://github.com/resourcelib/resourcelib/pull/71#issuecomment-414077918 too

**Comment by hakito** [comment]
Please check the PR #72 and I'll release it today.

**Comment by hakito** [comment]
It seems the AppVeyor build failed for the tag build. What did I wrong?

**Comment by thoemmi** [comment]
@hakito GitVersion was confused because the `v2.0` tag was not in the `master` branch.
I deleted that tag and tagged the most recent commit in the master branch. v2.0 is released by now.

I updated the RELEASING.md that the version tag must be added to a commit in the `master` branch. I also made preparations for the next version (v2.1 presumably).
