### ISSUE TITLE
Assembly name changed in version 2.0.0

### ISSUE THREAD

**Issue by jairbubbles** [resourcelib/resourcelib#73]
![image](https://user-images.githubusercontent.com/15875066/51103069-b0097100-17e1-11e9-920d-7833444d1d50.png)

I don't know if it's intended but in our case we have issues with that with a custom NuGet resolver / pugin system.

Anyway I feel like it would be more "normal" to keep the previous name which has the good taste to be the name of the NuGet package.

**Comment by jairbubbles** [comment]
@thoemmi Can you publish as 2.0.1? I checked `Vestris.resourcelib.2.1.0-beta0005.nupkg` and the content was ok.

**Comment by thoemmi** [comment]
It's now published as [2.1](https://www.nuget.org/packages/Vestris.ResourceLib/2.1.0).

**Comment by thoemmi** [comment]
(Actually, it should be 3.0, because it's a breaking change. But I guess we can agree on 2.1)
